version: '3.0'
services:
  app:
    build: .
    image: laravel_example
    container_name: laravel_example
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/example-app
    volumes:
      - .:/var/www/example-app
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
        - laravel_example

  webserver:
    image: nginx:alpine
    container_name: nginxexampleapp
    restart: unless-stopped
    tty: true
    ports:
    - "2022:80"
    volumes:
      - .:/var/www/example-app
      - ./storage/:/etc/nginx/conf.d/
    networks:
        - laravel_example

    #NETWORKS
networks:
  laravel_example:
    driver: bridge

#VOLUMES
volumes:
  lbdata:
    driver: local
